### ISSUE TITLE
how to visualize the result ?

### ISSUE THREAD

**Issue by michael-sz** [Terminal-K/MambaMOS#1]

**Comment by Terminal-K** [comment]
Hi, @michael-sz 
You can follow the guidelines of [LiDAR-MOS](https://github.com/PRBonn/LiDAR-MOS?tab=readme-ov-file#how-to-visualize-the-predictions) for visualizing single scan. If you need to achieve the visualization effect in the paper, concatenate the continuous 8 scans of point cloud files and their corresponding predictions beforehand.

**Comment by michael-sz** [comment]
@Terminal-K got it!  it will be beffter if you can add visualizied part.

**Comment by iwander-all** [comment]
@Terminal-K Hello, I am still do not know how to visualize as I am not familiar with Lidar-MOS. How to understand the output file in `MambaMOS/exp/semantic_kitti/mambamos/result`? For example, in seq 08 of kitti, the res 08_000000.npy and ori scan data 000000.bin has different item nums, how to understand your result and I want to vis it myself, thanks.


```
/home/hunkyu/net/MOS/MambaMOS/exp/semantic_kitti/mambamos/result/08_000000.npy
(987112,)
int64
/home/hunkyu/net/data/SemanticKitti/sequences/08/velodyne/000000.bin
(123389, 3)
float64

/home/hunkyu/net/MOS/MambaMOS/exp/semantic_kitti/mambamos/result/08_000001.npy
(987156,)
int64
/home/hunkyu/net/data/SemanticKitti/sequences/08/velodyne/000001.bin
(123433, 3)
float64

/home/hunkyu/net/MOS/MambaMOS/exp/semantic_kitti/mambamos/result/08_000002.npy
(986926,)
int64
/home/hunkyu/net/data/SemanticKitti/sequences/08/velodyne/000002.bin
(123159, 3)
float64

/home/hunkyu/net/MOS/MambaMOS/exp/semantic_kitti/mambamos/result/08_000003.npy
(986606,)
int64
/home/hunkyu/net/data/SemanticKitti/sequences/08/velodyne/000003.bin
(123069, 3)
float64

```

**Comment by Terminal-K** [comment]
Hi, @iwander-all 
The npy files in the "result" folder contain the predicted results of _N_ scans of point clouds stacked together. Therefore, the number of points in the npy file may not match the number of points in a single scan of the dataset (bin files). This npy file is used to load previously predicted results when the prediction is interrupted. Meanwhile, the corresponding single-scan prediction results for the dataset are the label files under "result/submit" (such as "result/submit/000000.label" is the result of "000000.bin" in sequence 08).

In addition, I may organize and publish my visualization program before October. I appreciate your understanding as I have been very busy lately.
