### ISSUE TITLE
About the point cloud input representation

### ISSUE THREAD

**Issue by softword-tt** [Terminal-K/MambaMOS#3]
Hi, thanks for your excellent work! I’m unfamiliar with the Pointcept workflow and confused about the Input Representation in section 3.2 of the paper. My understanding of the code is that the inputs are coord, strength, and tn. I want to ask if the points' strength is also used as input for the network during the learning process.
![image](https://github.com/user-attachments/assets/d325a498-6490-4ce2-ae17-7788ac652c2a)

**Comment by Terminal-K** [comment]
Hi, @softword-tt 
Apologies for the late reply! Yes, we combine the strength information of each point with its coordinates and timestamp as input. So the point representation should be $` p_i^{\prime}=\left[x_i, y_i, z_i, s_i, t_i\right]^T `$, where $`s_i`$ is the strength of each point. There is an error in the paper's description, sorry for the confusion caused.
As the config file:
https://github.com/Terminal-K/MambaMOS/blob/78370d0f022d0e6cb3a56d98342e7ae1014e440c/configs/semantic_kitti/semseg_mambamos.py#L100-L104
The data in ‘feat_keys’ will be collected by the class 'Collect' in the [transform.py](https://github.com/Terminal-K/MambaMOS/blob/78370d0f022d0e6cb3a56d98342e7ae1014e440c/pointcept/datasets/transform.py#L26) as input features.
